// descriptor.js — GENERATED by the panel editor from the drawn interface.
// The module's ports and params fall out of the drawing; edit them in the editor,
// not here. The factory (hand-written) implements behaviour against these ids.

export default {
  "apiVersion": 1,
  "id": "sine-source",
  "name": "Sine Source",
  "params": [
    {
      "id": "freq",
      "name": "Frequency",
      "min": 20,
      "max": 2000,
      "default": 220,
      "unit": "Hz",
      "curve": "exp"
    }
  ],
  "ports": [
    {
      "id": "out",
      "name": "Out",
      "domain": "audio",
      "dir": "out"
    }
  ]
};
