// designer-save.js — shared panel-editor save logic.
//
// Used by both the in-app IPC handler (electron-main) and the standalone dev server
// (designer-server). Writes a module's files and regenerates its panels. CommonJS so
// electron-main can require it; designer-server imports its default. gen-panel is run
// through our own binary — plain Node in the dev server, Electron-as-Node in the app
// (ELECTRON_RUN_AS_NODE is ignored by real Node, so one code path serves both).
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { execFile } = require('node:child_process');

const MODULE_DIRS = new Set(['complex-oscillator-259t', 'lpg-292', 'function-gen-281t', 'mixer', 'gallery']);
const SAFE_DIR = /^[a-z0-9][a-z0-9-]*$/;

const GEN_TEMPLATE = `// Generated by the panel editor. Renders panel.layout.js to the light + dark SVGs
// via the shared renderer, applying panel.overrides.json if present.
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { renderPanel } from '../../panel/render.js';
import { applyOverrides } from '../../panel/overrides.js';
import layout from './panel.layout.js';

const dir = fileURLToPath(new URL('.', import.meta.url));
const ovPath = dir + 'panel.overrides.json';
if (fs.existsSync(ovPath)) applyOverrides(layout, JSON.parse(fs.readFileSync(ovPath, 'utf8')));
fs.writeFileSync(dir + 'panel.svg', renderPanel(layout, false));
fs.writeFileSync(dir + 'panel.dark.svg', renderPanel(layout, true));
console.log('wrote panel.svg + panel.dark.svg');
`;

const DESC_HEADER = `// descriptor.js — GENERATED by the panel editor from the drawn interface.
// The module's ports and params fall out of the drawing; edit them in the editor,
// not here. The factory (hand-written) implements behaviour against these ids.

`;

function regen(root, modDir) {
  return new Promise((resolve, reject) => {
    execFile(process.execPath, [path.join(modDir, 'gen-panel.js')],
      { cwd: root, env: { ...process.env, ELECTRON_RUN_AS_NODE: '1' } },
      (err, _o, stderr) => (err ? reject(new Error(String(stderr || err))) : resolve()));
  });
}

// Two save shapes, mirroring the editor:
//   { dir, overrides }                        -> shipped module: write overrides, regen SVGs
//   { dir, editorOwned, layout, descriptor }  -> authored module: write layout + generated
//                                                descriptor + gen-panel, regen SVGs
// Returns { ok, ... } or { error }.
async function savePanel(root, msg) {
  const dir = msg && msg.dir;
  try {
    if (msg && msg.editorOwned) {
      if (!SAFE_DIR.test(dir || '')) return { error: `unsafe module dir "${dir}"` };
      if (!msg.layout || !msg.descriptor) return { error: 'missing layout/descriptor' };
      const modDir = path.join(root, 'modules', dir);
      if (!modDir.startsWith(path.join(root, 'modules') + path.sep)) return { error: 'bad path' };
      fs.mkdirSync(modDir, { recursive: true });
      fs.writeFileSync(path.join(modDir, 'panel.layout.js'), 'export default ' + JSON.stringify(msg.layout, null, 2) + ';\n');
      fs.writeFileSync(path.join(modDir, 'descriptor.js'), DESC_HEADER + 'export default ' + JSON.stringify(msg.descriptor, null, 2) + ';\n');
      fs.writeFileSync(path.join(modDir, 'gen-panel.js'), GEN_TEMPLATE);
      await regen(root, modDir);
      return { ok: true, dir };
    }
    if (!MODULE_DIRS.has(dir)) return { error: `unknown module "${dir}"` };
    const overrides = msg.overrides;
    if (!overrides || typeof overrides !== 'object') return { error: 'no overrides' };
    const modDir = path.join(root, 'modules', dir);
    const ovPath = path.join(modDir, 'panel.overrides.json');
    if (Object.keys(overrides).length) fs.writeFileSync(ovPath, JSON.stringify(overrides, null, 2) + '\n');
    else if (fs.existsSync(ovPath)) fs.unlinkSync(ovPath);   // empty = back to the pristine layout
    await regen(root, modDir);
    return { ok: true, overrides };
  } catch (e) {
    return { error: String((e && e.message) || e) };
  }
}

module.exports = { savePanel };
