// renderer.js — LibreModular audio-generation spike.
//
// This is implementation milestones one and two in a single page:
//
//   Milestone 1 — App shell + audio bootstrap. A first user click creates
//   the AudioContext (browsers, and Electron's Chromium renderer, require a
//   user gesture before audio can start) and plays a plain native
//   OscillatorNode. This proves the app can make sound at all and that the
//   click-to-start plumbing works inside the real Electron window.
//
//   Milestone 2 — Worklet pipeline. A second control loads the worklet
//   module over the app:// origin and plays a tone generated by the
//   TestToneProcessor. This proves the AudioWorklet toolchain end to end:
//   module loading, processor registration, glitch-free execution on the
//   audio thread, and parameter messages reaching the processor. The DSP is
//   a naive sine on purpose so any failure here is a pipeline failure, not
//   a synthesis bug.
//
// Nothing here is part of the real synth. It is scaffolding whose only job
// is to retire the toolchain risk before the module abstraction is drafted.
// The temporary controls double as the throwaway debug surface: they let
// you hear that the worklet responds to frequency and gain changes, which
// quietly validates the destination-side glide the GXW bridge will use.

'use strict';

// A single shared AudioContext for the whole spike, created lazily on the
// first user gesture. The real synth will own its context the same way.
let audioCtx = null;

// Native-oscillator handles (milestone 1).
let nativeOsc = null;
let nativeGain = null;

// Worklet handles (milestone 2).
let workletNode = null;
let workletReady = false;

const log = (msg) => {
  const el = document.getElementById('log');
  const line = document.createElement('div');
  line.textContent = msg;
  el.appendChild(line);
  el.scrollTop = el.scrollHeight;
};

function ensureContext() {
  if (audioCtx === null) {
    audioCtx = new AudioContext();
    log(`AudioContext created — sampleRate ${audioCtx.sampleRate} Hz, ` +
        `state "${audioCtx.state}".`);
    log(`crossOriginIsolated = ${self.crossOriginIsolated} ` +
        `(true means SharedArrayBuffer is available for the future ` +
        `WASM-DSP route).`);
  }
  // A context can start in "suspended" state; the gesture lets us resume it.
  if (audioCtx.state === 'suspended') {
    audioCtx.resume();
  }
  return audioCtx;
}

// --- Milestone 1: native oscillator ---

function startNativeTone() {
  const ctx = ensureContext();
  if (nativeOsc !== null) return; // already running

  nativeOsc = ctx.createOscillator();
  nativeGain = ctx.createGain();
  nativeOsc.type = 'sine';
  nativeOsc.frequency.value = 330;
  // Ramp gain up smoothly rather than clicking on.
  nativeGain.gain.value = 0;
  nativeGain.gain.setTargetAtTime(0.2, ctx.currentTime, 0.02);
  nativeOsc.connect(nativeGain).connect(ctx.destination);
  nativeOsc.start();
  log('Native OscillatorNode started at 330 Hz. If you hear this, the ' +
      'audio path and click-to-start gesture both work.');
}

function stopNativeTone() {
  if (nativeOsc === null) return;
  const ctx = audioCtx;
  nativeGain.gain.setTargetAtTime(0, ctx.currentTime, 0.02);
  const oscToStop = nativeOsc;
  // Stop after the fade so it doesn't click off.
  setTimeout(() => {
    try { oscToStop.stop(); } catch (_e) { /* already stopped */ }
  }, 120);
  nativeOsc = null;
  nativeGain = null;
  log('Native tone stopped.');
}

// --- Milestone 2: worklet ---

async function initWorklet() {
  const ctx = ensureContext();
  if (workletReady) return;
  try {
    // The module path is served by the app:// scheme handler with the
    // isolation headers attached. A leading slash makes it resolve against
    // the app origin root regardless of the current document path.
    await ctx.audioWorklet.addModule('/worklets/test-tone-processor.js');
    workletReady = true;
    log('Worklet module loaded and "test-tone" processor registered. ' +
        'The toolchain works.');
  } catch (err) {
    log(`WORKLET LOAD FAILED: ${err && err.message ? err.message : err}`);
    log('This is the risk the spike exists to find. If you see this, the ' +
        'worklet toolchain — not the DSP — is what needs attention.');
  }
}

async function startWorkletTone() {
  const ctx = ensureContext();
  await initWorklet();
  if (!workletReady) return;
  if (workletNode !== null) return;

  workletNode = new AudioWorkletNode(ctx, 'test-tone', {
    numberOfInputs: 0,
    numberOfOutputs: 1,
    outputChannelCount: [2],
  });
  workletNode.connect(ctx.destination);
  // noteOn opens the amplitude with a glide inside the processor.
  workletNode.port.postMessage({ type: 'noteOn', freq: 220 });
  log('Worklet tone started at 220 Hz (band-limited PolyBLEP replaces this ' +
      'sine at a later milestone). Move the frequency slider to hear the ' +
      'destination-side glide.');
}

function stopWorkletTone() {
  if (workletNode === null) return;
  workletNode.port.postMessage({ type: 'noteOff' });
  const nodeToStop = workletNode;
  setTimeout(() => {
    try { nodeToStop.disconnect(); } catch (_e) { /* already gone */ }
  }, 120);
  workletNode = null;
  log('Worklet tone stopped.');
}

function setWorkletFreq(hz) {
  if (workletNode === null) return;
  workletNode.port.postMessage({ type: 'setFreq', value: hz });
}

// --- Wiring ---

window.addEventListener('DOMContentLoaded', () => {
  if (window.wcoast && window.wcoast.isElectron) {
    log(`Running in Electron — Chromium ${window.wcoast.versions.chrome}, ` +
        `Node ${window.wcoast.versions.node}.`);
  } else {
    log('Preload bridge not found — running outside Electron?');
  }

  document.getElementById('nativeStart').addEventListener('click', startNativeTone);
  document.getElementById('nativeStop').addEventListener('click', stopNativeTone);
  document.getElementById('workletStart').addEventListener('click', startWorkletTone);
  document.getElementById('workletStop').addEventListener('click', stopWorkletTone);

  const freq = document.getElementById('freq');
  const freqLabel = document.getElementById('freqLabel');
  freq.addEventListener('input', () => {
    const hz = Number(freq.value);
    freqLabel.textContent = `${hz} Hz`;
    setWorkletFreq(hz);
  });

  log('Ready. Click "Play native tone" first, then "Play worklet tone".');
});
